name: Deploy PR to Test Environment

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number to Deploy'
        required: true
        type: number

jobs:
  deploy:
    uses: jardakotesovec/pkp-test-vps-ci/.github/workflows/deploy.yaml@main
    with:
      project: ojs
      branch: main # Dummy value; overridden by pr_number logic
      pr_number: ${{ inputs.pr_number }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.TEST_VPS_CI_SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.TEST_VPS_CI_SSH_HOST }}
      SSH_USERNAME: ${{ secrets.TEST_VPS_CI_SSH_USERNAME }}
