name: Deploy Branch to Test Environments

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to Deploy'
        required: true
        type: string
      copies:
        description: 'Comma-separated suffixes for additional copies (e.g., qa,hosting)'
        required: false
        type: string
        default: 'qa,hosting'

jobs:
  deploy:
    concurrency:
      group: deploy-branch-${{ inputs.branch }} # Group by branch (e.g., "deploy-branch-main")
      cancel-in-progress: true
    uses: jardakotesovec/pkp-test-vps-ci/.github/workflows/deploy.yaml@main
    with:
      project: ojs
      branch: ${{ inputs.branch }}
      copies: ${{ inputs.copies }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.TEST_VPS_CI_SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.TEST_VPS_CI_SSH_HOST }}
      SSH_USERNAME: ${{ secrets.TEST_VPS_CI_SSH_USERNAME }}
