name: Test VPS Deploy PR

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/deploy') &&
      (github.event.comment.author_association == 'OWNER' ||
       github.event.comment.author_association == 'MEMBER' ||
       github.event.comment.author_association == 'COLLABORATOR')
    concurrency:
      group: deploy-pr-${{ github.event.issue.number }} # Group by PR number (e.g., "deploy-pr-123")
      cancel-in-progress: true
    uses: jardakotesovec/pkp-test-vps-ci/.github/workflows/deploy.yaml@main
    with:
      project: ${{ github.event.repository.name }}
      pr_number: ${{ github.event.issue.number }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.TEST_VPS_CI_SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.TEST_VPS_CI_SSH_HOST }}
      SSH_USERNAME: ${{ secrets.TEST_VPS_CI_SSH_USERNAME }}
